# -*- coding: utf-8 -*-
"""AI_Resume_Reviewer

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JWdTPCNs3MRc-SUqmCCcJTrck3ISqyKu
"""

!pip install -q llama-cpp-python langchain langchain-community PyMuPDF gradio

from langchain.llms import LlamaCpp
from langchain.prompts import PromptTemplate
from langchain.chains import LLMChain

!wget -O llama-model.gguf "https://huggingface.co/second-state/TinyLlama-1.1B-Chat-v1.0-GGUF/resolve/main/TinyLlama-1.1B-Chat-v1.0-Q4_K_M.gguf"


import fitz, gradio as gr
from langchain.llms import LlamaCpp
from langchain.prompts import PromptTemplate
from langchain.chains import LLMChain

#  Load LLaMA via llama.cpp
llm = LlamaCpp(model_path="llama-model.gguf", n_ctx=2048, temperature=0.5, max_tokens=1024)

#  Prompt Template
template = """You are a professional resume reviewer.

Given the resume below, provide:
1. A 3-line summary
2. Top 3 strengths
3. Weaknesses or missing info
4. 2 suggestions to improve
5. 5 ATS keywords to add

Resume:
{resume_text}
"""
prompt = PromptTemplate(input_variables=["resume_text"], template=template)
chain = LLMChain(llm=llm, prompt=prompt)

#  Extract + Clean PDF
def extract_text_from_pdf(file_obj):
    with fitz.open(file_obj.name) as doc:
        txt = "".join(page.get_text() for page in doc)
    seen, out = {}, []
    for line in txt.split("\n"):
        l = line.strip()
        if not l: continue
        seen[l] = seen.get(l, 0) + 1
        if seen[l] <= 2: out.append(l)
    return "\n".join(out)[:2000]

# Review function
def review_resume(file_obj):
    text = extract_text_from_pdf(file_obj)
    try:
        return chain.run(resume_text=text).strip()
    except Exception as e:
        return f"[ERROR] {e}"

# Launch UI
gr.Interface(
    fn=review_resume,
    inputs=gr.File(label="📄 Upload Resume PDF"),
    outputs=gr.Textbox(label="🧠 Offline LLaMA Feedback"),
    title="Offline Resume Reviewer (LLaMA + LangChain)",
    description="Fully offline reviewer using LLaMA-1.1B Chat with LangChain."
).launch()